name: build
on:
  push:
    branches: [ master ]
jobs:
  coverage:
    runs-on: "ubuntu-latest"
    name: coverage
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: "Download the Code Climate test reporter"
      run: |
        mkdir -p tmp/
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
        chmod +x ./tmp/cc-test-reporter
    - shell: bash
      name: "Update build fingerprint"
      run: | 
        npm ci
        npm run build > tmp/build
        cat tmp/build
    - shell: bash
      name: "Create coverage for the React Stack"
      run: | 
        cd stacks/react
        npm ci
        npm run coverage
        ../../tmp/cc-test-reporter format-coverage -t lcov -o ../../tmp/codeclimate.react-stack.json --add-prefix react-stack
    - shell: bash
      name: "Create coverage for the SDK"
      run: | 
        cd sdk
        npm ci
        npm run build
        npm run coverage
        ../tmp/cc-test-reporter format-coverage -t lcov -o ../tmp/codeclimate.sdk.json --add-prefix sdk
    - shell: bash
      name: "Upload the combined coverage report to Code Climate"
      env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      run: | 
        ./tmp/cc-test-reporter sum-coverage tmp/codeclimate.*.json -p 2 -o tmp/codeclimate.total.json
        ./tmp/cc-test-reporter upload-coverage -i tmp/codeclimate.total.json
